export enum SubExchangeType {
    NONE = 'NONE',
    SUBVAR_ONLY = 'SUBVAR_ONLY',
    SUBVAR_WITH_ITEMS = 'SUBVAR_WITH_ITEMS',
    EXCHANGE_IS_SET_W_ITEMS = 'EXCHANGE_IS_SET_W_ITEMS',
    EXCHANGE_W_ITEMS = 'EXCHANGE_W_ITEMS',
}
